<?php
// quotes.php
$quotes = [
    "Nothing Changes if Nothing Changes.",
    "Someone else doesn't have to be wrong for you to be right.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful",
    "Circumstances do not make a man, they reveal him",
    "The calmer you are the clearer you think. Move with strategy, not emotion",
    "When anger rises, think of the consequences",
    "The day you plant the seed is not the day you eat the fruit.",
    "When the winds of change blow, some people build walls, and others build windmills.",
    "Don't feed every dog you see suffering. Some just need the strength to bite you.",
    "Believe you can and you're halfway there.",
    "Do not fear mistakes. You will know failure. Continue to reach out.",
    "The sky has no limits. Neither should you",
    "Dream as if you’ll live forever. Live as if you’ll die today.",
    "If you have no critics, you’ll likely have no success.",
    "Use your enemy's hand to catch a snake.",
    "It's always good to be underestimated.",
    "If you're afraid of failure, you don't deserve to be successful",
    "Be happy, but never satisfied.",
    "If you get on the wrong train, get off at the nearest station, the longer it takes you to get off, the more expensive the return trip will be.",
    "He who jumps into the void owes no explanation to those who stand and watch.",
    "f a brother teaches you how to fish,don't fish in his pond.",
    "The one who falls and gets up, is so much stronger than one who never fell.",
    "It does not matter how slowly you go as long as you do not stop.",
    "A mistake repeated more than once is a decision.",
    "A mistake that makes you humble is better than an achievement that makes you arrogant.",
    "Better to fight for something than live for nothing.",
    "Forget yesterday, live for today. Tomorrow will take care of itself.",
    "A person grows when they are forced to overcome their weaknesses.",
    "Unless you have bad times, you can't appreciate the good times.",
    "Strive not to be a success, but rather to be of value.",
    "Learn from the mistakes of others you can't live long enough to make them all yourselves.",
    "The future belongs to those who believe in the beauty of their dreams",
    "The attempt to escape from pain creates more pain",
    "You can’t have a better tomorrow if you are thinking about yesterday all the time.",
    "Be not afraid of going slowly. Be afraid of standing still",
    "The best view comes after the hardest climb.",
    "If you're afraid - don't do it, - if you're doing it - don't be afraid.",
    "The two most powerful warriors are patience and time",
    "Anger can be cured by time; but hatred cannot.",
    "If you can change your mind, you can change your life.",
    "Power is always dangerous. It attracts the worst and corrupts the best.",
    "Knowledge without action is wastefulness and action without knowledge is foolishness",
    "Man cannot remake himself without suffering, for he is both the marble and sculptor.",
    "Everything you say should be true but not everything true should be said. ",
    "We have two ears and one mouth so we can listen twice as much as we speak",
    "Don't watch the clock; do what it does. Keep going.",
    "Your body can stand almost anything. It's your mind that you have to convince",
    "Smart people want to learn. The rest teach",
    "Life is a tragedy for those who feel, and a comedy for those who think.",
    "Everything you can imagine is real.",
    "A snake can change its skin but not its disposition",
    "Hard work beats talent when talent doesn't work hard.",
    "The future depends on what you do today.",
    "Dream big, start small, but most of all, start.",
    "The only way to achieve the impossible is to believe it is possible.",
    "A journey of a thousand miles begins with a single step.",
    "Time is like cement, it takes time to become permanent.",
    "Time Changes, People Don,t",
    "Simple does not mean easy",
    "Life can be beautiful if you let it be",
    "Things get better until they get worse",
    "Love chnages Everything!",
    "You need power only when you want to do something harmful, otherwise love is enough to get everything done.- Charlie Chaplin",
    "There are a lot of little reasons, why the big things in our lives happen. ",
    "Don't chase, get chosen.",
    "Love the life you live. Live the life you love.",
    "Talking about our problems is our greatest addiction. Break the habit. Talk about your joys.",
    "Miracles come in moments. Be ready and willing ",
    "Strength is matter of a made up mind. ",
    "Hardship is what makes us stronger",
    "Trust your dreams even if they frighten you",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t wait for opportunity. Create it.",
    "Do something today that your future self will thank you for.",
    "It always seems impossible until it’s done.",
    "Just live a life without thinking about other's feelings about you.",
    "Dream it. Wish it. Do it.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wish it were easier. Wish you were better.",
    "Success is what happens after you’ve survived all your mistakes.",
    "Don't compare yourself with others. No one can play your role better than you.",
    "Your life does not get better by chance, it gets better by change.",
    "If you can dream it, you can do it.",
    "Start where you are. Use what you have. Do what you can.",
    "Success is the best revenge.",
    "Opportunities don’t happen. You create them.",
    "Great things never come from comfort zones.",
    "Stay True and Real.°",
    "Dream big and dare to fail.",
    "Your limitation—it’s only your imagination.",
    "Success usually comes to those who are too busy to be looking for it.",
    "I find that the harder I work, the more luck I seem to have.",
    "The way to get started is to quit talking and begin doing.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t let yesterday take up too much of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "It’s never too late to be what you might have been.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "A year from now you may wish you had started today.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Action is the foundational key to all success.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Do what you can with all you have, wherever you are.",
    "Don’t wait. The time will never be just right.",
    "Be not afraid of going slowly, be afraid only of standing still.",
    "Success is not in what you have, but who you are.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "Don’t be pushed by your problems, be led by your dreams.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your life does not get better by chance, it gets better by change.",
    "Go as far as you can see; when you get there, you’ll be able to see farther.",
    "The only person you are destined to become is the person you decide to be.",
    "Small daily improvements over time lead to stunning results.",
    "Do something today that your future self will thank you for.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You get what you focus on, so focus on what you want.",
    "You are capable of more than you know.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Start where you are. Use what you have. Do what you can.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Failure is success in progress.",
    "Success isn’t overnight. It’s when every day you get a little better than the day before.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Some people dream of success, while others wake up and work hard at it.",
    "If you want to achieve greatness stop asking for permission.",
    "The secret to getting ahead is getting started.",
    "Believe in yourself and all that you are.",
    "Opportunities don’t happen, you create them.",
    "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan.",
    "Whatever you can do, or dream you can, begin it.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The man who has confidence in himself gains the confidence of others.",
    "A goal is a dream with a deadline.",
    "The more you practice, the better you get.",
    "Don’t aim for success if you want it; just do what you love and believe in.",
    "Success is not measured by the position one has in life but by the obstacles one overcomes to get there.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Success comes from curiosity, concentration, perseverance, and self-criticism.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Success is not in what you have, but who you are.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Success is the best revenge.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Hustle until your haters ask if you're hiring.",
    "The best revenge is massive success.",
    "Don't wait for the storm to pass, learn to dance in the rain.",
    "You miss 100% of the shots you don't take.",
    "Believe you can and you're halfway there.",
    "Don't let your dreams just be dreams.",
    "Your only limit is your mind.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Do one thing every day that scares you.",
    "Life is short, make every hair flip count.",
    "Work hard in silence, let your success be your noise.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The best way to predict the future is to create it.",
    "Great things never came from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Don't stop when you're tired. Stop when you're done.",
    "You have to be at your strongest when you're feeling at your weakest.",
    "The hard days are what make you stronger.",
    "Success is what happens after you survive your mistakes.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "Don't watch the clock; do what it does. Keep going.",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Doubt kills more dreams than failure ever will.",
    "The secret to getting ahead is getting started.",
    "Difficult roads often lead to beautiful destinations.",
    "Success is the best revenge.",
    "Believe you can and you're halfway there.",
    "Start where you are. Use what you have. Do what you can.",
    "The best way out is always through.",
    "A little progress each day adds up to big results.",
    "Success doesn’t just find you. You have to go out and get it.",
    "It's not about perfect. It's about effort.",
    "Don’t wish for it. Work for it.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Set your goals high, and don't stop till you get there.",
    "The only place where success comes before work is in the dictionary.",
    "A goal is not always meant to be reached; it often serves simply as something to aim at.",
    "Success isn't always about greatness. It's about consistency.",
    "Success is nothing more than a few simple disciplines practiced every day.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "A journey of a thousand miles begins with a single step.",
    "Your life does not get better by chance, it gets better by change.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not in what you have, but who you are.",
    "Success is how high you bounce when you hit the bottom.",
    "Dream it. Wish it. Do it.",
    "You don't have to be great to start, but you have to start to be great.",
    "Work until you no longer have to introduce yourself.",
    "Success is the progressive realization of a worthy goal.",
    "Success is the best revenge.",
    "Don't be afraid to give up the good to go for the great.",
    "Success is what comes after your stop making excuses.",
    "Believe you can and you're halfway there.",
    "Success isn’t always about greatness. It’s about consistency.",
    "The secret to success is to know something nobody else knows.",
    "Success is not about the destination, it’s about the journey.",
    "Success is where preparation and opportunity meet.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only way to achieve the impossible is to believe it is possible.",
    "It’s not how far you fall, but how high you bounce that counts.",
    "The best revenge is massive success.",
    "If you can dream it, you can do it.",
    "Small daily improvements over time lead to stunning results.",
    "Work hard, stay consistent, and be patient.",
    "Stop doubting yourself, work hard, and make it happen.",
    "Success is to wake up each morning and consciously decide that today will be the best day of your life.",
    "There is no substitute for hard work.",
    "Dream big and dare to fail.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "In order to succeed, your desire for success should be greater than your fear of failure.",
    "Don’t count the days, make the days count.",
    "Success is no accident.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "If opportunity doesn’t knock, build a door.",
    "The best view comes after the hardest climb.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Success is the ability to go from failure to failure without losing your enthusiasm.",
    "You don't always get what you wish for. You get what you work for.",
    "Be a positive energy trampoline—absorb what you need and rebound more back.",
    "Success comes from having dreams that are bigger than your fears.",
    "Believe you can and you’re halfway there.",
    "Stop waiting for things to happen. Go out and make them happen.",
    "Success is 1% inspiration, 99% perspiration.",
    "Success occurs when your dreams get bigger than your excuses.",
    "Success is falling nine times and getting up ten.",
    "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Success is the sum of details.",
    "Success is dependent on effort.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don’t count the days, make the days count.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t let what you cannot do interfere with what you can do.",
    "The future depends on what you do today.",
    "Believe you can and you’re halfway there.",
    "Act as if what you do makes a difference. It does.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Your only limit is your mind.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Dream bigger. Do bigger.",
    "The best revenge is massive success.",
    "Work hard in silence, let your success be your noise.",
    "You don’t have to be perfect to be amazing.",
    "Doubt kills more dreams than failure ever will.",
    "Push yourself, because no one else is going to do it for you.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Opportunities don't happen, you create them.",
    "Success is how high you bounce when you hit bottom.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Hard work beats talent when talent doesn’t work hard.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "You only fail when you stop trying.",
    "If you're going through hell, keep going.",
    "Great things never come from comfort zones.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Dream it. Believe it. Build it.",
    "If you get tired, learn to rest, not quit.",
    "Don’t limit your challenges; challenge your limits.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "If you don’t build your dream, someone else will hire you to help them build theirs.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Every accomplishment starts with the decision to try.",
    "Don’t be afraid to give up the good to go for the great.",
    "There are no shortcuts to any place worth going.",
    "I never dreamed about success, I worked for it.",
    "Success is not in what you have, but who you are.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The secret of getting ahead is getting started.",
    "Success comes to those who hustle while they wait.",
    "You can’t have a million-dollar dream with a minimum-wage work ethic.",
    "It always seems impossible until it’s done.",
    "Be stubborn about your goals, but flexible about your methods.",
    "The key to success is to start before you are ready.",
    "What we achieve inwardly will change outer reality.",
    "The distance between insanity and genius is measured only by success.",
    "Success isn’t just about what you accomplish in your life, it’s about what you inspire others to do.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success is a journey, not a destination.",
    "Start where you are. Use what you have. Do what you can.",
    "You don’t have to see the whole staircase, just take the first step.",
    "Success doesn’t happen overnight. Keep your eye on the prize and don’t look back.",
    "Success is a state of mind. If you want success, start thinking of yourself as a success.",
    "The only way to achieve the impossible is to believe it is possible.",
    "A journey of a thousand miles begins with a single step.",
    "Don’t tell people your plans. Show them your results.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "Don’t wish it were easier; wish you were better.",
    "Be somebody who makes everybody feel like a somebody.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is not just about making money. It’s about making a difference.",
    "Success is best when it’s shared.",
    "Success is falling nine times and getting up ten.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Set your goals high, and don’t stop till you get there.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "It’s not about being the best. It’s about being better than you were yesterday.",
    "Your dreams don’t work unless you do.",
    "Success is what happens after you’ve survived all your mistakes.",
    "Be the kind of person that makes others want to up their game.",
    "It’s not how much you have that makes people look up to you, it’s who you are.",
    "Success means doing the best we can with what we have.",
    "The only time you fail is when you fall down and stay down.",
    "Success is not for the lazy.",
    "Don't be afraid to give up the good to go for the great.",
    "Success is found in your daily routine.",
    "You don't have to be the best to start, but you have to start to be the best.",
    "Success occurs when opportunity meets preparation.",
    "Success is not measured by money but by happiness.",
    "Success is never accidental.",
    "You are born to win.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t wait for opportunity, create it.",
    "Success is what happens when preparation meets opportunity.",
    "The road to success is always under construction.",
    "Success is about consistency.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Success is not about luck, it’s about hard work.",
    "Success starts with self-discipline.",
    "Success is about having a positive attitude.",
    "Success is not a destination, it’s a journey.",
    "There is no elevator to success; you have to take the stairs.",
    "Success is doing ordinary things extraordinarily well.",
    "Success is a series of small wins.",
    "Keep  showing up, no matter how you feel.",
    "A somebody is a somebody because somebody believed in them.",
    "A somebody was a once a nobody who decided to try.",
    "Never trust a person who betrays others even if he betrayed them for you.",
    "Invest your energy in those who truly value your time & presence",
    "Bad news: everything is temporary, which is also good news.",
];

// Return quotes as JSON
header('Content-Type: application/json');
echo json_encode($quotes);