<?php
// quotes.php
$quotes = [
    "Nothing Changes if Nothing Changes.",
    "Someone else doesn't have to be wrong for you to be right.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful",
    "Circumstances do not make a man, they reveal him",
    "The calmer you are the clearer you think. Move with strategy, not emotion",
    "When anger rises, think of the consequences",
    "The day you plant the seed is not the day you eat the fruit.",
    "When the winds of change blow, some people build walls, and others build windmills.",
    "Don't feed every dog you see suffering. Some just need the strength to bite you.",
    "Believe you can and you're halfway there.",
    "Do not fear mistakes. You will know failure. Continue to reach out.",
    "The sky has no limits. Neither should you",
    "Dream as if you’ll live forever. Live as if you’ll die today.",
    "If you have no critics, you’ll likely have no success.",
    "Use your enemy's hand to catch a snake.",
    "It's always good to be underestimated.",
    "If you're afraid of failure, you don't deserve to be successful",
    "Be happy, but never satisfied.",
    "If you get on the wrong train, get off at the nearest station, the longer it takes you to get off, the more expensive the return trip will be.",
    "He who jumps into the void owes no explanation to those who stand and watch.",
    "f a brother teaches you how to fish,don't fish in his pond.",
    "The one who falls and gets up, is so much stronger than one who never fell.",
    "It does not matter how slowly you go as long as you do not stop.",
    "A mistake repeated more than once is a decision.",
    "A mistake that makes you humble is better than an achievement that makes you arrogant.",
    "Better to fight for something than live for nothing.",
    "Forget yesterday, live for today. Tomorrow will take care of itself.",
    "A person grows when they are forced to overcome their weaknesses.",
    "Unless you have bad times, you can't appreciate the good times.",
    "Strive not to be a success, but rather to be of value.",
    "Learn from the mistakes of others you can't live long enough to make them all yourselves.",
    "The future belongs to those who believe in the beauty of their dreams",
    "The attempt to escape from pain creates more pain",
    "You can’t have a better tomorrow if you are thinking about yesterday all the time.",
    "Be not afraid of going slowly. Be afraid of standing still",
    "The best view comes after the hardest climb.",
    "If you're afraid - don't do it, - if you're doing it - don't be afraid.",
    "The two most powerful warriors are patience and time",
    "Anger can be cured by time; but hatred cannot.",
    "If you can change your mind, you can change your life.",
    "Power is always dangerous. It attracts the worst and corrupts the best.",
    "Knowledge without action is wastefulness and action without knowledge is foolishness",
    "Man cannot remake himself without suffering, for he is both the marble and sculptor.",
    "Everything you say should be true but not everything true should be said. ",
    "We have two ears and one mouth so we can listen twice as much as we speak",
    "Don't watch the clock; do what it does. Keep going.",
    "Your body can stand almost anything. It's your mind that you have to convince",
    "Smart people want to learn. The rest teach",
    "Life is a tragedy for those who feel, and a comedy for those who think.",
    "Everything you can imagine is real.",
    "A snake can change its skin but not its disposition",
    "Hard work beats talent when talent doesn't work hard.",
    "The future depends on what you do today.",
    "Dream big, start small, but most of all, start.",
    "The only way to achieve the impossible is to believe it is possible.",
    "A journey of a thousand miles begins with a single step.",
    "Time is like cement, it takes time to become permanent.",
    "Time Changes, People Don,t",
    "Simple does not mean easy",
    "Life can be beautiful if you let it be",
    "Things get better until they get worse",
    "Love chnages Everything!",
    "You need power only when you want to do something harmful, otherwise love is enough to get everything done.- Charlie Chaplin",
    "There are a lot of little reasons, why the big things in our lives happen. ",
    "Don't chase, get chosen.",
    "Love the life you live. Live the life you love.",
    "Talking about our problems is our greatest addiction. Break the habit. Talk about your joys.",
    "Miracles come in moments. Be ready and willing ",
    "Strength is matter of a made up mind. ",
    "Hardship is what makes us stronger",
    "Trust your dreams even if they frighten you",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t wait for opportunity. Create it.",
    "Do something today that your future self will thank you for.",
    "It always seems impossible until it’s done.",
    "Just live a life without thinking about other's feelings about you.",
    "Dream it. Wish it. Do it.",
    "The key to success is to focus on goals, not obstacles.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wish it were easier. Wish you were better.",
    "Success is what happens after you’ve survived all your mistakes.",
    "Don't compare yourself with others. No one can play your role better than you.",
    "Your life does not get better by chance, it gets better by change.",
    "If you can dream it, you can do it.",
    "Start where you are. Use what you have. Do what you can.",
    "Success is the best revenge.",
    "Opportunities don’t happen. You create them.",
    "Great things never come from comfort zones.",
    "Stay True and Real.°",
    "Dream big and dare to fail.",
    "Your limitation—it’s only your imagination.",
    "Success usually comes to those who are too busy to be looking for it.",
    "I find that the harder I work, the more luck I seem to have.",
    "The way to get started is to quit talking and begin doing.",
    "The only place where success comes before work is in the dictionary.",
    "Don’t let yesterday take up too much of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Don’t wait for the perfect moment. Take the moment and make it perfect.",
    "It’s never too late to be what you might have been.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "A year from now you may wish you had started today.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Action is the foundational key to all success.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Do what you can with all you have, wherever you are.",
    "Don’t wait. The time will never be just right.",
    "Be not afraid of going slowly, be afraid only of standing still.",
    "Success is not in what you have, but who you are.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "Don’t be pushed by your problems, be led by your dreams.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your life does not get better by chance, it gets better by change.",
    "Go as far as you can see; when you get there, you’ll be able to see farther.",
    "The only person you are destined to become is the person you decide to be.",
    "Small daily improvements over time lead to stunning results.",
    "Do something today that your future self will thank you for.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You get what you focus on, so focus on what you want.",
    "You are capable of more than you know.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Start where you are. Use what you have. Do what you can.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Failure is success in progress.",
    "Success isn’t overnight. It’s when every day you get a little better than the day before.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Some people dream of success, while others wake up and work hard at it.",
    "If you want to achieve greatness stop asking for permission.",
    "The secret to getting ahead is getting started.",
    "Believe in yourself and all that you are.",
    "Opportunities don’t happen, you create them.",
    "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan.",
    "Whatever you can do, or dream you can, begin it.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "The man who has confidence in himself gains the confidence of others.",
    "A goal is a dream with a deadline.",
    "The more you practice, the better you get.",
    "Don’t aim for success if you want it; just do what you love and believe in.",
    "Success is not measured by the position one has in life but by the obstacles one overcomes to get there.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "Success comes from curiosity, concentration, perseverance, and self-criticism.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Success is not in what you have, but who you are.",
    "It’s not whether you get knocked down, it’s whether you get up.",
    "Success is the best revenge.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Hustle until your haters ask if you're hiring.",
    "The best revenge is massive success.",
    "Don't wait for the storm to pass, learn to dance in the rain.",
    "You miss 100% of the shots you don't take.",
    "Believe you can and you're halfway there.",
    "Don't let your dreams just be dreams.",
    "Your only limit is your mind.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Do one thing every day that scares you.",
    "Life is short, make every hair flip count.",
    "Work hard in silence, let your success be your noise.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The best way to predict the future is to create it.",
    "Great things never came from comfort zones.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Don't stop when you're tired. Stop when you're done.",
    "You have to be at your strongest when you're feeling at your weakest.",
    "The hard days are what make you stronger.",
    "Success is what happens after you survive your mistakes.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "Don't watch the clock; do what it does. Keep going.",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Doubt kills more dreams than failure ever will.",
    "The secret to getting ahead is getting started.",
    "Difficult roads often lead to beautiful destinations.",
    "Success is the best revenge.",
    "Believe you can and you're halfway there.",
    "Start where you are. Use what you have. Do what you can.",
    "The best way out is always through.",
    "A little progress each day adds up to big results.",
    "Success doesn’t just find you. You have to go out and get it.",
    "It's not about perfect. It's about effort.",
    "Don’t wish for it. Work for it.",
    "Success is the result of preparation, hard work, and learning from failure.",
    "Set your goals high, and don't stop till you get there.",
    "The only place where success comes before work is in the dictionary.",
    "A goal is not always meant to be reached; it often serves simply as something to aim at.",
    "Success isn't always about greatness. It's about consistency.",
    "Success is nothing more than a few simple disciplines practiced every day.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "A journey of a thousand miles begins with a single step.",
    "Your life does not get better by chance, it gets better by change.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Success is not in what you have, but who you are.",
    "Success is how high you bounce when you hit the bottom.",
    "Dream it. Wish it. Do it.",
    "You don't have to be great to start, but you have to start to be great.",
    "Work until you no longer have to introduce yourself.",
    "Success is the progressive realization of a worthy goal.",
    "Success is the best revenge.",
    "Don't be afraid to give up the good to go for the great.",
    "Success is what comes after your stop making excuses.",
    "Believe you can and you're halfway there.",
    "Success isn’t always about greatness. It’s about consistency.",
    "The secret to success is to know something nobody else knows.",
    "Success is not about the destination, it’s about the journey.",
    "Success is where preparation and opportunity meet.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only way to achieve the impossible is to believe it is possible.",
    "It’s not how far you fall, but how high you bounce that counts.",
    "The best revenge is massive success.",
    "If you can dream it, you can do it.",
    "Small daily improvements over time lead to stunning results.",
    "Work hard, stay consistent, and be patient.",
    "Stop doubting yourself, work hard, and make it happen.",
    "Success is to wake up each morning and consciously decide that today will be the best day of your life.",
    "There is no substitute for hard work.",
    "Dream big and dare to fail.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "In order to succeed, your desire for success should be greater than your fear of failure.",
    "Don’t count the days, make the days count.",
    "Success is no accident.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "If opportunity doesn’t knock, build a door.",
    "The best view comes after the hardest climb.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Success is the ability to go from failure to failure without losing your enthusiasm.",
    "You don't always get what you wish for. You get what you work for.",
    "Be a positive energy trampoline—absorb what you need and rebound more back.",
    "Success comes from having dreams that are bigger than your fears.",
    "Believe you can and you’re halfway there.",
    "Stop waiting for things to happen. Go out and make them happen.",
    "Success is 1% inspiration, 99% perspiration.",
    "Success occurs when your dreams get bigger than your excuses.",
    "Success is falling nine times and getting up ten.",
    "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Success is the sum of details.",
    "Success is dependent on effort.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "Don’t count the days, make the days count.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don’t let what you cannot do interfere with what you can do.",
    "The future depends on what you do today.",
    "Believe you can and you’re halfway there.",
    "Act as if what you do makes a difference. It does.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Your only limit is your mind.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Dream bigger. Do bigger.",
    "The best revenge is massive success.",
    "Work hard in silence, let your success be your noise.",
    "You don’t have to be perfect to be amazing.",
    "Doubt kills more dreams than failure ever will.",
    "Push yourself, because no one else is going to do it for you.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Opportunities don't happen, you create them.",
    "Success is how high you bounce when you hit bottom.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Hard work beats talent when talent doesn’t work hard.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "You only fail when you stop trying.",
    "If you're going through hell, keep going.",
    "Great things never come from comfort zones.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Dream it. Believe it. Build it.",
    "If you get tired, learn to rest, not quit.",
    "Don’t limit your challenges; challenge your limits.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "If you don’t build your dream, someone else will hire you to help them build theirs.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Every accomplishment starts with the decision to try.",
    "Don’t be afraid to give up the good to go for the great.",
    "There are no shortcuts to any place worth going.",
    "I never dreamed about success, I worked for it.",
    "Success is not in what you have, but who you are.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The secret of getting ahead is getting started.",
    "Success comes to those who hustle while they wait.",
    "You can’t have a million-dollar dream with a minimum-wage work ethic.",
    "It always seems impossible until it’s done.",
    "Be stubborn about your goals, but flexible about your methods.",
    "The key to success is to start before you are ready.",
    "What we achieve inwardly will change outer reality.",
    "The distance between insanity and genius is measured only by success.",
    "Success isn’t just about what you accomplish in your life, it’s about what you inspire others to do.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success is a journey, not a destination.",
    "Start where you are. Use what you have. Do what you can.",
    "You don’t have to see the whole staircase, just take the first step.",
    "Success doesn’t happen overnight. Keep your eye on the prize and don’t look back.",
    "Success is a state of mind. If you want success, start thinking of yourself as a success.",
    "The only way to achieve the impossible is to believe it is possible.",
    "A journey of a thousand miles begins with a single step.",
    "Don’t tell people your plans. Show them your results.",
    "The more you praise and celebrate your life, the more there is in life to celebrate.",
    "Don’t wish it were easier; wish you were better.",
    "Be somebody who makes everybody feel like a somebody.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success is not just about making money. It’s about making a difference.",
    "Success is best when it’s shared.",
    "Success is falling nine times and getting up ten.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Set your goals high, and don’t stop till you get there.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "It’s not about being the best. It’s about being better than you were yesterday.",
    "Your dreams don’t work unless you do.",
    "Success is what happens after you’ve survived all your mistakes.",
    "Be the kind of person that makes others want to up their game.",
    "It’s not how much you have that makes people look up to you, it’s who you are.",
    "Success means doing the best we can with what we have.",
    "The only time you fail is when you fall down and stay down.",
    "Success is not for the lazy.",
    "Don't be afraid to give up the good to go for the great.",
    "Success is found in your daily routine.",
    "You don't have to be the best to start, but you have to start to be the best.",
    "Success occurs when opportunity meets preparation.",
    "Success is not measured by money but by happiness.",
    "Success is never accidental.",
    "You are born to win.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Don’t wait for opportunity, create it.",
    "Success is what happens when preparation meets opportunity.",
    "The road to success is always under construction.",
    "Success is about consistency.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Success is not about luck, it’s about hard work.",
    "Success starts with self-discipline.",
    "Success is about having a positive attitude.",
    "Success is not a destination, it’s a journey.",
    "There is no elevator to success; you have to take the stairs.",
    "Success is doing ordinary things extraordinarily well.",
    "Success is a series of small wins.",
    "Keep  showing up, no matter how you feel.",
    "A somebody is a somebody because somebody believed in them.",
    "A somebody was a once a nobody who decided to try.",
    "Never trust a person who betrays others even if he betrayed them for you.",
    "Invest your energy in those who truly value your time & presence",
    "Bad news: everything is temporary, which is also good news.",
    "Each new day is blank page- write a good story",
    "Don't be afraid to start over. It's a chance to build something better this time.",
    "Sometimes you win, sometimes you learn.",
    "The best way to gain self-confidence is to do what you are afraid to do.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "Once you decide what you want everyday has more meaning.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not in what you have, but who you are.",
    "He who fears he shall suffer, already suffers what he fears.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "If you look at the world, you'll be distressed. If you look within, you'll be depressed. If you look at God you'll be at rest",
    "Trust your own instinct. Your mistakes might as well be your own, instead of someone elses. ",
    "The best way out is always through.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within  us.",
    "Believe you can and you're halfway there.",
    "Memory is the mother of all wisdom.",
    "The only journey is the one within.",
    "Keep true to the dreams of thy youth. ",
    "Happiness depends upon ourselves.",
    "Act as if what you do makes a difference. It does.",
    "Stop chasing the wrong one. The right one won 't run.",
    "Sometimes we are tested not to show our weaknesses, but to discover our strengths.",
    "Don't be afraid to give up the good to go for the great.",
    "The best revenge is massive success.",
    "The only way to do great work is to love what you do.",
    "Worry is a misuse of imagination.",
    "Success is not in what you have, but who you are.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Every story has An end  but, in life every ending  is just A new beginning.  ",
    "Believe you can and you're halfway there.",
    "Don't watch the clock; do what it does. Keep going.",
    "If being happy is important to you, try this: instead of regretting all you lack, celebrate all you've got.—Brian Vaszily",
    "You're always with yourself, so you might as well enjoy the company.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Nobody cares unless you win- so win!",
    "Be like the ocean, which is never afraid of the storm.",
    "Success is not in what you have, but who you are.",
    "Be like the ocean, calm on the surface, but always deep underneath.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Believe you can and you're halfway there.",
    "Never argue with stupid people, they will drag you down to their level and then beat you with experience.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "Sit alone you will be with your best company.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Sit alone you will find answers within yourself.",
    "Believe you can and you're halfway there.",
    "Don't put your weapon away just because your enemy smiled.",
    "Time Will tell you everything you need to know.",
    "All you need is sometime for yourself to recharge your soul.",
    "The most dangerous form of blindness is believing that your perspective is the only reality.",
    "Success is not in what you have, but who you are.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "He who lacks the courage to risk his life for freedom deserves to be a slave.",
    "Believe you can and you're halfway there.",
    "Peace is found not in perfection, but in the acceptance of imperfection.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "Sometimes you have to stand alone to prove that you can still stand.",
    "The world bows to those who act, not those who wait.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Believe you can and you're halfway there.",
    "Death is not the greatest loss in life. The greatest loss is what dies inside while still alive.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "Death is not an enemy,A wasted life is.",
    "Success is not in what you have, but who you are.",
    "The urge to save humanity is almost always a false front for the urge to rule it.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The worst person is the one who sees himself better than others.",
    "Believe you can and you're halfway there.",
    "The tongue is so powerful, speak good over your life at all times.",
    "work until your bank account looks like a phone number",
    "The fears we dont face become our limits.",
    "Doubt kills more dreams than failure ever will.",
    "Somewhere between the silence and the spin, the forest remembered me.",
    "And if, you love, love their darkness too, not just their light.",
    "Stars can't shine without darkness.",
    "In the middle of every difficulty lies opportunity.",
    "The silence after surviving a day that no one knew was hard.",
    "Everything we see is a perspective, Not the truth.",
    "Sometimes the wrong choices bring us to the right places.",
    "Your vibe attracts your tribe.",
    "Sometimes the wait is longer Because the blessing is bigger.",
    "The only way to do great work is to love what you do.",
    "Vibe alone until you are valued.",
    "Success is not in what you have, but who you are.",
    "When nails grow long. we cut nails, not fingers. Similarly, when misunderstanding grows up. Cut your ego, not your Relationship.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Believe you can and you're halfway there.",
    "Don't let the fear of losing be greater than the excitement of winning.",
    "The only sure way to avoid making mistakes is to have no new ideas." ,
    "Trying to get everyone to like you is a sign of mediocrity." ,
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Courage is doing what you are afraid to do. There can be no courage unless you are scared." ,
    "The first problem for all of us, men and women, is not to learn, but to unlearn",
    "Knowledge comes, but wisdom lingers",
    "The invariable mark of wisdom is to see the miraculous in the common",
    "You have power over your mind—not outside events. Realize this, and you will find strength",
    "A man who dares waste one hour of time has not discovered the value of life",
    "He who knows all the answers has not been asked all the questions",
    "To acquire knowledge, one must study; but to acquire wisdom, one must observe",
    "It is easier to find a score of men wise enough to discover the truth than to find one intrepid enough, in the face of opposition, to stand up for it",
    "Learning without thinking is useless. Thinking without learning is dangerous",
    "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn",
    "Wonder is the beginning of wisdom",
    "The meaning of life is whatever you ascribe it to be. Being alive is the meaning",
    "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them",
    "In order to exist, man must rebel",
    "It all depends on how we look at things, and not how they are in themselves",
    "What we see depends mainly on what we look for",
    "The best way out is always through",
    "Man is the only creature that refuses to be what he is",
    "The greatest tragedy for any human being is going through their entire lives believing the only perspective that matters is their own",
    "Life is a succession of lessons which must be lived to be understood",
    "The mind is everything. What you think you become.",
    "If you want to lift yourself up, lift up someone else.",
    "Where there is a will, there is a way.",
    "Attitude is a little thing that makes a big difference.",
    "The purpose of our lives is to be happy.",
    "I attribute my success to this: I never gave or took any excuse.",
    "Strive for progress, not perfection.",
    "The best revenge is living well.",
    "We are what we repeatedly do. Excellence, therefore, is not an act but a habit.",
    "In the middle of difficulty lies opportunity.",
    "The only true wisdom is in knowing you know nothing.",
    "Happiness is not something readymade. It comes from your own actions.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "I would rather die of passion than of boredom.",
    "The journey of a thousand miles must begin with a single step.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Only I can change my life. No one can do it for me.",
    "Life is really simple, but men insist on making it complicated.",
    "Change the world by being yourself.",
    "Nothing is impossible, the word itself says 'I'm possible'!",
    "It is during our darkest moments that we must focus to see the light.",
    "The only way around is through.",
    "The future belongs to those who prepare for it today.",
    "Life is a succession of lessons which must be lived to be understood.",
    "Imagination is the beginning of creation.",
    "Try not to become a man of success, but rather try to become a man of value.",
    "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
    "Don't count the days, make the days count.",
    "You must do the things you think you cannot do.",
    "What consumes your mind controls your life.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Every moment is a fresh beginning.",
    "The best preparation for tomorrow is doing your best today.",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "Be the change that you wish to see in the world.",
    "Tough times never last, but tough people do.",
    "Our greatest weakness lies in giving up.",
    "We can't help everyone, but everyone can help someone.",
    "The best way to get started is to stop talking and start doing.",
    "You define your own life. Don't let other people write your script.",
    "The only true wisdom is in knowing you know nothing.",
    "The difference between ordinary and extraordinary is that little extra.",
    "The past cannot be changed. The future is yet in your power.",
    "May your choices reflect your hopes, not your fears.",
    "The power of imagination makes us infinite.",
    "Don’t be afraid to sparkle.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "The struggle you’re in today is developing the strength you need for tomorrow.",
    "An investment in knowledge always pays the best interest.",
    "Don't let the noise of others' opinions drown out your own inner voice.",
    "The only person you should try to be better than is the person you were yesterday.",
    "If you are not willing to learn, no one can help you. If you are determined to learn, no one can stop you.",
    "The goal is not to be perfect by the end, the goal is to be better today.",
    "You have to expect things of yourself before you can do them.",
    "The master has failed more times than the beginner has even tried.",
    "Your life is your message to the world. Make sure it's inspiring.",
    "We are what we pretend to be, so we must be careful about what we pretend to be.",
    "If you have good thoughts they will shine out of your face like sunbeams.",
    "The best way to predict the future is to invent it.",
    "It takes courage to grow up and become who you really are.",
    "The best time for new beginnings is now.",
    "Life is about making an impact, not an income.",
    "Do what is right, not what is easy.",
    "The road to success and the road to failure are almost exactly the same.",
    "If you want to go fast, go alone. If you want to go far, go together.",
    "Integrity is doing the right thing, even when no one is watching.",
    "Happiness is not an absence of problems, but the ability to deal with them.",
    "When you cease to dream, you cease to live.",
    "The greatest mistake you can make in life is to be continually fearing you will make one.",
    "Change your thoughts and you change your world.",
    "A smooth sea never made a skilled sailor.",
    "In order to carry a positive action, we must develop here a positive vision.",
    "The grass is greener where you water it.",
    "What you seek is seeking you.",
    "The mind once stretched by a new idea never returns to its original dimensions.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "The only true eloquence is in a heart that can say what it means.",
    "The quieter you become, the more you are able to hear.",
    "He who is not courageous enough to take risks will accomplish nothing in life.",
    "The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
    "Be kind, for everyone you meet is fighting a harder battle.",
    "Where focus goes, energy flows.",
    "The greatest test of courage on earth is to bear defeat without losing heart.",
    "The only journey is the one within.",
    "The world is a book and those who do not travel read only one page.",
    "The best time to repair the roof is when the sun is shining.",
    "Give light, and people will find the way.",
    "The highest result of education is tolerance.",
    "Judge a man by his questions rather than by his answers.",
    "It is better to light a candle than curse the darkness.",
    "Life is either a daring adventure or nothing at all.",
    "The purpose of life is a life of purpose.",
    "We first make our habits, then our habits make us.",
    "The greatest prison people live in is the fear of what other people think.",
    "When we strive to become better than we are, everything around us becomes better too.",
    "To improve is to change; to be perfect is to change often.",
    "Everything has its beauty, but not everyone sees it.",
    "The true sign of intelligence is not knowledge but imagination.",
    "It is never too late to be what you might have been.",
    "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy.",
    "The secret of happiness is freedom, the secret of freedom is courage.",
    "The mind is like a parachute, it works best when it's open.",
    "The only person who can pull me down is myself, and I’m not going to allow her.",
    "If you can't be good, be careful.",
    "Wherever you go, go with all your heart.",
    "The art of life is to know how to enjoy a little and to endure much.",
    "Don't wait for extraordinary opportunities. Seize common occasions and make them great.",
    "The journey is the reward.",
    "Be not the slave of your desires, but the master of your mind.",
    "It is better to lead from behind and to put others in front, especially when you celebrate victory.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "Patience is not simply the ability to wait, it's how we behave while we are waiting.",
    "The greatest weapon against stress is our ability to choose one thought over another.",
    "Where performance is measured, performance improves. Where performance is measured and reported, the rate of improvement accelerates.",
    "Every strike brings me closer to the next home run.",
    "We must let go of the life we have planned, so as to accept the life that is waiting for us.",
    "The tragedy of life is not that it ends so soon, but that we wait so long to begin it.",
    "If you obey all the rules, you miss all the fun.",
    "Happiness is an inside job.",
    "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
    "I didn't fail the test. I just found 100 ways to do it wrong.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "You miss 100% of the shots you don't take.",
    "When you change the way you look at things, the things you look at change.",
    "The most difficult thing is the decision to act, the rest is merely tenacity.",
    "The price of anything is the amount of life you exchange for it.",
    "If you want to be happy, be.",
    "We are all in the gutter, but some of us are looking at the stars.",
    "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
    "The mind is not a vessel to be filled, but a fire to be kindled.",
    "You must be the change you wish to see in the world.",
    "The question isn't who is going to let me; it's who is going to stop me.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Our lives begin to end the day we become silent about things that matter.",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    "Don't cry because it's over, smile because it happened.",
    "The only journey is the one within.",
    "We suffer more often in imagination than in reality.",
    "We are products of our past, but we don't have to be prisoners of it.",
    "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    "The way to love anything is to realize that it may be lost.",
    "Waste no more time arguing about what a good man should be. Be one.",
    "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.",
    "The unexamined life is not worth living.",
    "Change your life today. Don't gamble on the future, act now, without delay.",
    "Man's mind, once stretched by a new idea, never regains its original dimensions.",
    "The only difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.",
    "The only courage that matters is the kind that gets you from one moment to the next.",
    "Never spend your money before you have earned it.",
    "The best way to cheer yourself is to try to cheer someone else up.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "If you genuinely want something, don’t wait for it—teach yourself to be impatient.",
    "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The surest way not to fail is to determine to succeed.",
    "The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
    "When you talk, you are only repeating what you already know. But if you listen, you may learn something new.",
    "The time is always right to do what is right.",
    "We cannot solve problems with the kind of thinking we employed when we came up with them.",
    "Our character is what we do when we think no one is looking.",
    "Don’t let yesterday use up too much of today.",
    "The measure of who we are is what we do with what we have.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "You take your life in your own hands, and what happens? A terrible thing: no one to blame.",
    "We must dare to invent the future.",
    "Simplicity is the ultimate sophistication.",
    "Where there is love there is life.",
    "The best way to escape from a problem is to solve it.",
    "The world is changed by your example, not by your opinion.",
    "Action may not always bring happiness, but there is no happiness without action.",
    "Patience is bitter, but its fruit is sweet.",
    "The successful warrior is the average man, with laser-like focus.",
    "It is not the mountain we conquer, but ourselves.",
    "In great attempts it is glorious even to fail.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "Fall seven times, stand up eight.",
    "He who is contented with what he has, is a rich man.",
    "A journey is best measured in friends, rather than miles.",
    "The future starts today, not tomorrow.",
    "If you are going through hell, keep going.",
    "If you tell the truth, you don't have to remember anything.",
    "The man who moves a mountain begins by carrying away small stones.",
    "The secret of success is constancy to purpose.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.",
    "The best way to appreciate your job is to imagine yourself without one.",
    "The greatest discovery of all time is that a human can alter his future by merely altering his attitude.",
    "When written in Chinese, the word 'crisis' is composed of two characters. One represents danger and the other represents opportunity.",
    "The difference between the impossible and the possible lies in a man's determination.",
    "Never too old, never too bad, never too late, never too sick to start from scratch once again.",
    "The greatest antidote to exhaustion is not necessarily rest, but wholehearted completeness.",
    "The only things you regret are the risks you didn't take.",
    "The only source of knowledge is experience.",
    "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.",
    "We are what we believe we are.",
    "Nothing is so fatiguing as the eternal hanging on of an uncompleted task.",
    "The man who has confidence in himself gains the confidence of others.",
    "The greatest discovery is that a human being can alter his life by altering his attitudes.",
    "The best preparation for good work tomorrow is to do good work today.",
    "Where observation is concerned, chance favors only the prepared mind.",
    "The world needs dreamers and the world needs doers. But above all, the world needs dreamers who do.",
    "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not.",
    "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
    "A wise man makes his own decisions, an ignorant man follows the public opinion.",
    "You must take the time to define your own path and not blindly follow others.",
    "The quieter you become, the more you are able to hear.",
    "Do not seek to follow in the footsteps of the wise; seek what they sought.",
    "The measure of a man is what he does with power.",
    "The greatest antidote to anger is delay.",
    "Every new day is a chance to change your life.",
    "You can have results or excuses, but not both.",
    "We do not remember days, we remember moments.",
    "Don't let the fear of time stop you from starting; time will pass anyway.",
    "The moment you doubt whether you can fly, you cease forever to be able to do it.",
    "Wheresoever you go, go with all your heart.",
    "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all.",
    "Live out of your imagination, not your history.",
    "We may encounter many defeats but we must not be defeated.",
    "Try to be a rainbow in someone else's cloud.",
    "The best way to escape from a problem is to solve it.",
    "The only true wisdom is in knowing you know nothing.",
    "It is better to be hated for what you are than loved for what you are not.",
    "The price of success is hard work, dedication to the job at hand, and the determination that whether we win or lose, we have applied the best of ourselves to the task at hand.",
    "Build your own dreams, or someone else will hire you to build theirs.",
    "You can’t cross the sea merely by standing and staring at the water.",
    "There is no great genius without some touch of madness.",
    "If you wish to be great, begin from the bottom.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
    "The man who says he can and the man who says he can't are both usually right.",
    "If you don't like something, change it. If you can't change it, change your attitude.",
    "Action is the antidote to despair.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.",
    "Our greatest primary need is to be understood.",
    "Self-pity is easily the most destructive of the non-pharmaceutical narcotics.",
    "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
    "Your greatest responsibility is to honor the calling of your soul.",
    "Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally.",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.",
    "If you want to make enemies, try to change something.",
    "Do not wait to strike till the iron is hot; but make the iron hot by striking.",
    "The best index to a person's character is how he treats people who can't do him any good, and how he treats people who can't fight back.",
    "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    "The foolish man seeks happiness in the distance; the wise grows it under his feet.",
    "He who controls others may be powerful, but he who has mastered himself is mightier still.",
    "The only way to have a friend is to be one.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "You can't depend on your eyes when your imagination is out of focus.",
    "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
    "Where there is no struggle, there is no strength.",
    "What you do speaks so loudly that I cannot hear what you say.",
    "The best dreams happen when you’re awake.",
    "Character is the ability to carry out a good resolution long after the excitement of the moment has passed.",
    "It takes a great deal of bravery to stand up to your enemies, but a great deal more to stand up to your friends.",
    "The greatest accomplishment is not in never falling, but in rising again after you fall.",
    "The future belongs to those who prepare for it today.",
    "Judge a man by his questions rather than by his answers.",
    "The mind that opens to a new idea never returns to its original size.",
    "When you finally free yourself from the need for external validation, you'll discover a happiness that is truly your own.",
    "If you have integrity, nothing else matters. If you don't have integrity, nothing else matters.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
    "Everything is theoretically impossible until it is done.",
    "It's not about being better than someone else, it's about being better than you used to be.",
    "The only way to deal with fear is to face it.",
    "The difference between a boss and a leader is that a boss says 'Go!', and a leader says 'Let's go!'",
    "A ship in harbor is safe, but that is not what ships are built for.",
    "The first step is always the hardest, but once you take it, everything else becomes a little easier.",
    "When we are no longer able to change a situation, we are challenged to change ourselves.",
    "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.",
    "We are shaped by our thoughts; we become what we think.",
    "The greatest fear in the world is the opinions of others. And the moment you are unafraid of the crowd, you are no longer a sheep, you become a lion.",
    "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.",
    "Do not follow where the path may lead. Go instead where there is no path and leave a trail.",
    "You cannot shake hands with a clenched fist.",
    "The best way to know yourself is to accept yourself.",
    "The best and most efficient way to provide for the future is to take care of the present.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "You cannot teach a man anything; you can only help him discover it within himself.",
    "The biggest risk is not taking any risk.",
    "Don't let yesterday take up too much of today.",
    "The power of a man's virtue should not be measured by his extraordinary efforts, but by his everyday conduct.",
    "A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power.",
    "We are most alive when we're in love.",
    "The future is not something we enter. The future is something we create.",
    "Change your thoughts and you change your world.",
    "Everything you can imagine is real.",
    "He who has a why to live can bear almost any how.",
    "The successful warrior is the average man, with laser-like focus.",
    "Where performance is measured, performance improves.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Life is a mirror and will reflect back to the thinker what he thinks into it.",
    "You must expect great things of yourself before you can do them.",
    "It is not the years in your life but the life in your years that counts.",
    "The measure of success is not whether you have a tough problem to deal with, but whether it is the same problem you had last year.",
    "Do not take life too seriously. You will never get out of it alive.",
    "The world is a stage, but the play is badly cast.",
    "The greatest pleasure in life is doing what people say you cannot do.",
    "The foundation stones for a balanced success are honesty, character, integrity, faith, love and loyalty.",
    "If you think you are too small to make a difference, try sleeping with a mosquito.",
    "A journey of a thousand miles begins with a single step.",
    "The only true failure is when you stop trying.",
    "You cannot find peace by avoiding life.",
    "You cannot swim for new horizons until you have the courage to lose sight of the shore.",
    "It's not the load that breaks you down, it's the way you carry it.",
    "The world breaks everyone, and afterward, many are strong at the broken places.",
    "Don't lower your standards for anyone or anything. Self-respect is everything.",
    "The only journey is the one within.",
    "Be brave. Take risks. Nothing can substitute experience.",
    "The difference between the successful and the unsuccessful is the former are willing to do what the latter are not.",
    "We should not give up and we should not allow the problem to defeat us.",
    "Everything has its time, and everything passes.",
    "The best way to escape the labyrinth is to embrace it.",
    "A lack of boundaries invites a lack of respect.",
    "Your reputation is more important than your paycheck, and your integrity is worth more than your career.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "The quieter you become, the more you are able to hear.",
    "Nothing is permanent in this wicked world, not even our troubles.",
    "Man can live about forty days without food, about three days without water, about eight minutes without air, but only one second without hope.",
    "The greatest challenge in life is discovering who you are. The second greatest is being happy with what you find.",
    "A grateful mind is a great mind which eventually attracts to itself great things.",
    "Whenever you are confronted with an opponent, conquer him with love.",
    "The future is something which everyone reaches at the rate of sixty minutes an hour, whatever he does, whoever he is.",
    "The mind is not a vessel to be filled, but a fire to be kindled.",
    "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.",
    "You cannot shake hands with a clenched fist.",
    "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "We are what we pretend to be, so we must be careful about what we pretend to be.",
    "I would rather walk with a friend in the dark, than alone in the light.",
    "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.",
    "Do not let the past distract you from the present, and do not let the present prevent you from planning the future.",
    "Excellence is not a skill. It is an attitude.",
    "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.",
    "The first and great commandment is: Don't let them scare you.",
    "You cannot find peace by avoiding life.",
    "The most courageous act is still to think for yourself. Aloud.",
    "Man is a creature of a thousand moods, but he who understands himself is a rarity.",
    "The only person you are destined to become is the person you decide to be.",
    "Courage is knowing what not to fear.",
    "The greatest pleasure in life is doing what people say you cannot do.",
    "The best way to predict the future is to create it.",
    "The reward of a thing well done is to have done it.",
    "When you are inspired by some great purpose, all your thoughts break their bonds.",
    "The biggest risk is not taking any risk. In a world that is changing really quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "Don't be pushed by your problems. Be led by your dreams.",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate.",
    "It is hard to fail, but it is worse never to have tried to succeed.",
    "To love oneself is the beginning of a lifelong romance.",
    "The greatest antidote to anger is delay.",
    "Patience, persistence and perspiration make an unbeatable combination for success.",
    "A man who is a master of patience is master of everything else.",
    "The art of being wise is the art of knowing what to overlook.",
    "Worry does not empty tomorrow of its sorrow, it empties today of its strength.",
    "The first step toward change is awareness. The second step is acceptance.",
    "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not.",
    "If you want to go fast, go alone. If you want to go far, go together.",
    "The foolish man seeks happiness in the distance; the wise grows it under his feet.",
    "Your current situation is not your final destination.",
    "Life is short, and it is up to you to make it sweet.",
    "The only way to have a friend is to be one.",
    "Whenever you are creating beauty around you, you are restoring your own soul.",
    "You can't cross the sea merely by standing and staring at the water.",
    "The best fighter is never angry.",
    "The secret of success is to do the common thing uncommonly well.",
    "Don't find fault, find a remedy.",
    "The way to get things done is not to mind who gets the credit for doing them.",
    "Nothing is stronger than a broken man who has rebuilt himself.",
    "We cannot control the wind, but we can direct the sail.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "You must take the time to define your own path and not blindly follow others.",
    "When anger rises, think of the consequences.",
    "The man who has confidence in himself gains the confidence of others.",
    "The mind is everything. What you think you become.",
    "If you can't be good, be careful.",
    "The greatest obstacle to discovery is not ignorance—it is the illusion of knowledge.",
    "It is not what happens to you, but how you react to it that matters.",
    "The only thing we have to fear is fear itself.",
    "You must expect great things of yourself before you can do them.",
    "Life is a tragedy for those who feel, and a comedy for those who think.",
    "Simplicity is the ultimate sophistication.",
    "It is better to be hated for what you are than loved for what you are not.",
    "The highest endeavor is to be a person who decides to be one's own best friend.",
    "If you obey all the rules, you miss all the fun.",
    "The art of life is to know how to enjoy a little and to endure much.",
    "You have power over your mind—not outside events. Realize this, and you will find strength.",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.",
    "The best revenge is living well.",
    "Where there is a will, there is a way.",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    "We must dare to invent the future.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    "A man's worth is no greater than his ambitions.",
    "The purpose of life is to live it, to taste experience to the utmost.",
    "If you tell the truth, you don't have to remember anything.",
    "The man who moves a mountain begins by carrying away small stones.",
    "You only live once, but if you do it right, once is enough.",
    "We suffer more often in imagination than in reality.",
    "A journey is best measured in friends, rather than miles.",
    "The secret of success is constancy to purpose.",
    "When written in Chinese, the word 'crisis' is composed of two characters. One represents danger and the other represents opportunity.",
    "The mind once stretched by a new idea never returns to its original dimensions.",
    "It is better to light a candle than curse the darkness."



];

// Return quotes as JSON
header('Content-Type: application/json');
echo json_encode($quotes);
